# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190513_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '个人博客', 'verbose_name_plural': '个人博客'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户列表', 'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('title', 'blog')]),
        ),
    ]
