# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190514_0855'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('title', 'blog')]),
        ),
    ]
