# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190514_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩数'),
        ),
        migrations.AddField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('title', 'blog')]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('title', 'blog')]),
        ),
    ]
